// Centralized Hugeicons mapping for the portfolio.
import {
  Github01Icon,
  Linkedin02Icon,
  NewTwitterIcon,
  DiscordIcon,
  TelegramIcon,
  WhatsappIcon,
  ShieldEnergyIcon,
  TestTube01Icon,
  CodeIcon,
  CodeSquareIcon,
  Database02Icon,
  ServerStack02Icon,
  ChromeIcon,
  ReactIcon,
  TailwindcssIcon,
  GitBranchIcon,
  Clock01Icon,
  ArrowExpand01Icon,
  Cancel01Icon,
  ArrowLeft02Icon,
  ArrowRight02Icon,
  Image01Icon,
  FloppyDiskIcon,
  Add01Icon,
  Delete02Icon,
  Edit02Icon,
  Upload04Icon,
  Tag01Icon,
  PackageIcon,
  Alert02Icon,
  Sun01Icon,
  Moon02Icon,
  Copy01Icon,
  Tick02Icon,
  ArrowUp02Icon,
  ArrowDown02Icon,
  Link01Icon,
  Wrench01Icon,
  ComputerTerminal01Icon,
} from 'hugeicons-react';

export const Icons = {
  github: Github01Icon,
  linkedin: Linkedin02Icon,
  twitter: NewTwitterIcon,
  discord: DiscordIcon,
  telegram: TelegramIcon,
  whatsapp: WhatsappIcon,
  linux: ComputerTerminal01Icon,
  security: ShieldEnergyIcon,
  chemistry: TestTube01Icon,
  code: CodeIcon,
  codeSquare: CodeSquareIcon,
  database: Database02Icon,
  server: ServerStack02Icon,
  chrome: ChromeIcon,
  react: ReactIcon,
  tailwind: TailwindcssIcon,
  branch: GitBranchIcon,
  hardware: Wrench01Icon,
  clock: Clock01Icon,
  expand: ArrowExpand01Icon,
  close: Cancel01Icon,
  prev: ArrowLeft02Icon,
  next: ArrowRight02Icon,
  external: Link01Icon,
  image: Image01Icon,
  save: FloppyDiskIcon,
  add: Add01Icon,
  delete: Delete02Icon,
  edit: Edit02Icon,
  upload: Upload04Icon,
  tag: Tag01Icon,
  box: PackageIcon,
  alert: Alert02Icon,
  sun: Sun01Icon,
  moon: Moon02Icon,
  copy: Copy01Icon,
  check: Tick02Icon,
  up: ArrowUp02Icon,
  down: ArrowDown02Icon,
  link: Link01Icon,
};

export default Icons;
