// Centralized Hugeicons mapping for the portfolio.
// Use these named exports throughout the app instead of mixing icon libraries.
import {
  Github01Icon,
  LinkedinIcon,
  NewTwitterIcon,
  DiscordIcon,
  TelegramIcon,
  WhatsappIcon,
  Linux01Icon,
  ShieldEnergyIcon,
  TestTube01Icon,
  CodeIcon,
  CodeSquareIcon,
  Database02Icon,
  Server02Icon,
  GoogleChromeIcon,
  ReactIcon,
  TailwindcssIcon,
  GitBranchIcon,
  Clock04Icon,
  ArrowExpandIcon,
  Cancel01Icon,
  ArrowLeft02Icon,
  ArrowRight02Icon,
  ExternalLink04Icon,
  Image01Icon,
  FloppyDiskIcon,
  Add01Icon,
  Delete02Icon,
  Edit02Icon,
  Upload04Icon,
  Tag01Icon,
  Box01Icon,
  Alert02Icon,
  Sun01Icon,
  Moon02Icon,
  Copy01Icon,
  Tick02Icon,
  ArrowUp02Icon,
  ArrowDown02Icon,
  Link01Icon,
  Wrench02Icon,
} from 'hugeicons-react';

export const Icons = {
  // Socials
  github: Github01Icon,
  linkedin: LinkedinIcon,
  twitter: NewTwitterIcon,
  discord: DiscordIcon,
  telegram: TelegramIcon,
  whatsapp: WhatsappIcon,

  // Tech / categories
  linux: Linux01Icon,
  security: ShieldEnergyIcon,
  chemistry: TestTube01Icon,
  code: CodeIcon,
  codeSquare: CodeSquareIcon,
  database: Database02Icon,
  server: Server02Icon,
  chrome: GoogleChromeIcon,
  react: ReactIcon,
  tailwind: TailwindcssIcon,
  branch: GitBranchIcon,
  hardware: Wrench02Icon,

  // Actions / UI
  clock: Clock04Icon,
  expand: ArrowExpandIcon,
  close: Cancel01Icon,
  prev: ArrowLeft02Icon,
  next: ArrowRight02Icon,
  external: ExternalLink04Icon,
  image: Image01Icon,
  save: FloppyDiskIcon,
  add: Add01Icon,
  delete: Delete02Icon,
  edit: Edit02Icon,
  upload: Upload04Icon,
  tag: Tag01Icon,
  box: Box01Icon,
  alert: Alert02Icon,
  sun: Sun01Icon,
  moon: Moon02Icon,
  copy: Copy01Icon,
  check: Tick02Icon,
  up: ArrowUp02Icon,
  down: ArrowDown02Icon,
  link: Link01Icon,
};

export default Icons;
